# Generated by Django 2.1.5 on 2019-04-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='received_date',
            field=models.DateField(null=True),
        ),
    ]
