# Generated by Django 2.1.5 on 2019-04-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawitem',
            name='item_name',
            field=models.CharField(max_length=50),
        ),
    ]
