# Generated by Django 2.1.5 on 2019-04-12 09:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_auto_20190318_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='production_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
